# Using the name variable with the URL in line 13 is conviniet
# when copying and pasting from another recipe, but not really needed.
{% set name = "fluidsynth" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FluidSynth/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1df5a1afb91acf3b945b7fdb89ac0d99877622161d9b5155533da59113eaaa20

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - compilers
  host:
    - glib
    - libsndfile
    - readline
  run:
    - libsndfile

test:
  commands:
    - fluidsynth --help

about:
  home: http://www.fluidsynth.org
  license: GPL-2.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Real-time software synthesizer based on the SoundFont 2 specs

  description: |
    Real-time software synthesizer based on the SoundFont 2 specs.
  doc_url: https://github.com/FluidSynth/fluidsynth/wiki/
  dev_url: http://www.fluidsynth.org/api/

extra:
  recipe-maintainers:
    - ngam
    - stefan-balke
