{% set version = "2.2.8" %}

package:
  name: fluidsynth
  version: {{ version }}

source:
  url: https://github.com/FluidSynth/fluidsynth/archive/v{{ version }}.tar.gz
  sha256: 7c29a5cb7a2755c8012d941d1335da7bda957bbb0a86b7c59215d26773bb51fe

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("fluidsynth", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - compilers
  host:
    - glib
    - libsndfile
    - readline
  run:
    - libsndfile

test:
  commands:
    - fluidsynth --help

about:
  home: http://www.fluidsynth.org
  license: GPL-2.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Real-time software synthesizer based on the SoundFont 2 specs

  description: |
    Real-time software synthesizer based on the SoundFont 2 specs.
  doc_url: https://github.com/FluidSynth/fluidsynth/wiki/
  dev_url: http://www.fluidsynth.org/api/

extra:
  recipe-maintainers:
    - ngam
    - stefan-balke
