# Using the name variable with the URL in line 13 is conviniet
# when copying and pasting from another recipe, but not really needed.
{% set name = "fluidsynth" %}
{% set version = "2.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FluidSynth/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a254efceff5d99f8d658d12d25318317f37307e6df852ec9baeb7da173496967

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - pkg-config
  host:
    - glib
    - libsndfile
    - readline
  run:
    - libsndfile

test:
  commands:
    - fluidsynth --help

about:
  home: http://www.fluidsynth.org
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Real-time software synthesizer based on the SoundFont 2 specs

  description: |
    Real-time software synthesizer based on the SoundFont 2 specs.
  doc_url: https://github.com/FluidSynth/fluidsynth/wiki/
  dev_url: http://www.fluidsynth.org/api/

extra:
  recipe-maintainers:
    - stefan-balke
